import { requireUser } from "../../lib/auth";
import { db } from "../../lib/db";
import WorkspaceFrame from "../../components/WorkspaceFrame";

export default async function Exports() {
  const user = await requireUser();
  const rows = await db.export.findMany({ where: { userId: user.id }, orderBy: { createdAt: "desc" }, take: 100, include: { clip: true } });
  return <WorkspaceFrame active="/exports" email={user.email} eyebrow="Delivery library" title="Exports" description="Download completed renders from your projects." action={<span className="rounded-lg border border-white/[.08] bg-white/[.025] px-3 py-2 text-xs text-zinc-400">{rows.length} records</span>}>
    {rows.length === 0 ? <div className="rounded-2xl border border-dashed border-white/[.12] bg-white/[.012] px-6 py-16 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl border border-white/[.08] text-xl text-[#c4f36b]">↗</div><h2 className="mt-4 text-lg font-semibold">Nothing exported yet</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-zinc-500">Once a clip has been rendered and exported, its real export record will show up here.</p><a href="/dashboard" className="cf-button mt-5">Open a project ↗</a></div> : <div className="overflow-hidden rounded-2xl border border-white/[.08] bg-[#10141a]"><div className="grid grid-cols-[1fr_auto] gap-3 border-b border-white/[.07] px-5 py-3 text-[10px] font-semibold uppercase tracking-[.14em] text-zinc-600"><span>File / source clip</span><span>Delivery</span></div><div className="divide-y divide-white/[.06]">{rows.map(row=><article key={row.id} className="grid grid-cols-[1fr_auto] items-center gap-4 px-5 py-4"><div className="flex min-w-0 items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/[.07] bg-white/[.025] text-[#c4f36b]">▶</div><div className="min-w-0"><div className="truncate text-sm font-medium">{row.clip?.title || row.clip?.category || `Clip ${row.clipId.slice(0, 8)}`}</div><div className="mt-1 text-[10px] text-zinc-600">Created {row.createdAt.toLocaleString("en-IN")}</div></div></div><a href={`/api/exports/${row.id}`} className="cf-button-secondary !min-h-9 !px-3 !text-xs">↓ Download</a></article>)}</div></div>}
  </WorkspaceFrame>;
}
