import Link from "next/link";
import { requireUser } from "../../lib/auth";
import { db } from "../../lib/db";

export default async function TemplatesPage() {
  const user = await requireUser();
  const templates = await db.template.findMany({ where: { userId: user.id }, orderBy: { updatedAt: "desc" } });
  return <main className="min-h-screen"><header className="border-b border-white/[.07]"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/dashboard" className="text-xs text-[#9ca6b4] hover:text-white">← Workspace</Link><Link href="/project/new" className="cf-button cf-button-primary">＋ New project</Link></div></header><section className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><p className="cf-eyebrow">Repeatable creative settings</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.06em]">Templates</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#8792a1]">Saved editing configurations from your account. Template creation and application depend on the editor workflow available in this build.</p>{templates.length===0?<div className="cf-panel mt-8 rounded-2xl p-8 sm:p-12"><span className="grid h-11 w-11 place-items-center rounded-xl bg-white/[.04] text-xl text-[#c4f56b]">◫</span><h2 className="mt-5 text-xl font-semibold">No templates saved yet.</h2><p className="mt-2 max-w-lg text-sm leading-6 text-[#8792a1]">When you save an editing configuration, it will be listed here. We don't display sample templates as if they belonged to your account.</p><Link href="/dashboard" className="cf-button cf-button-secondary mt-5">Return to workspace</Link></div>:<div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{templates.map(template=><article key={template.id} className="cf-panel rounded-2xl p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#c4f56b]/[.07] text-lg text-[#c4f56b]">◫</span><h2 className="mt-5 text-sm font-semibold">{template.name}</h2><p className="mt-2 text-[10px] text-[#687383]">Updated {template.updatedAt.toLocaleString()}</p><pre className="mt-4 max-h-40 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-black/20 p-3 text-[9px] leading-5 text-[#8792a1]">{JSON.stringify(template.settings,null,2)}</pre></article>)}</div>}</section></main>;
}
