import { requireUser } from "../../lib/auth";
import { db } from "../../lib/db";
import CancelButton from "./CancelButton";
import WorkspaceFrame from "../../components/WorkspaceFrame";

function dateParts(value: Date) {
  return { day: value.toLocaleDateString("en-IN", { day: "2-digit" }), month: value.toLocaleDateString("en-IN", { month: "short" }), full: value.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) };
}

export default async function Calendar() {
  const user = await requireUser();
  const rows = await db.scheduledPost.findMany({ where: { userId: user.id }, orderBy: { scheduledFor: "asc" }, include: { clip: true, socialConnection: true } });
  const upcoming = rows.filter(row => row.scheduledFor.getTime() >= Date.now() && ["SCHEDULED", "PUBLISHING"].includes(row.status)).length;
  const published = rows.filter(row => row.status === "PUBLISHED").length;
  return <WorkspaceFrame active="/calendar" email={user.email} eyebrow="Publishing" title="Calendar" description="Track scheduled posts and the status returned by connected platforms." action={<span className="rounded-lg border border-white/[.08] bg-white/[.025] px-3 py-2 text-xs text-zinc-400">{rows.length} records</span>}>
    <div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/[.07] bg-[#10141a] p-4"><div className="text-[10px] uppercase tracking-wider text-zinc-600">All scheduled posts</div><div className="mt-2 text-2xl font-semibold">{rows.length}</div></div><div className="rounded-xl border border-white/[.07] bg-[#10141a] p-4"><div className="text-[10px] uppercase tracking-wider text-zinc-600">Upcoming / active</div><div className="mt-2 text-2xl font-semibold text-[#c4f36b]">{upcoming}</div></div><div className="rounded-xl border border-white/[.07] bg-[#10141a] p-4"><div className="text-[10px] uppercase tracking-wider text-zinc-600">Published</div><div className="mt-2 text-2xl font-semibold">{published}</div></div></div>
    {rows.length === 0 ? <div className="rounded-2xl border border-dashed border-white/[.12] bg-white/[.012] px-6 py-16 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl border border-white/[.08] text-xl text-[#c4f36b]">▦</div><h2 className="mt-4 text-lg font-semibold">Your publishing queue is empty</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-zinc-500">Connect an eligible publishing account and schedule a real clip to see it here. No example posts are mixed into your calendar.</p><a href="/settings" className="cf-button mt-5">Connect an account ↗</a></div> : <div className="overflow-hidden rounded-2xl border border-white/[.08] bg-[#10141a]"><div className="grid grid-cols-[1fr_auto] gap-3 border-b border-white/[.07] px-5 py-3 text-[10px] font-semibold uppercase tracking-[.14em] text-zinc-600"><span>Scheduled content</span><span>Status</span></div><div className="divide-y divide-white/[.06]">{rows.map(row => { const date = dateParts(row.scheduledFor); return <article key={row.id} className="grid grid-cols-[1fr_auto] gap-4 px-5 py-4"><div className="flex min-w-0 gap-3"><div className="flex h-14 w-14 shrink-0 flex-col items-center justify-center rounded-xl border border-white/[.07] bg-white/[.025]"><span className="text-lg font-semibold">{date.day}</span><span className="text-[9px] uppercase text-zinc-500">{date.month}</span></div><div className="min-w-0 self-center"><div className="truncate text-sm font-medium">{row.clip?.title || row.clip?.category || "Scheduled clip"}</div><div className="mt-1 text-xs text-zinc-500">{date.full}</div><div className="mt-1 text-[10px] text-zinc-600">{row.socialConnection?.provider ?? "No provider"} · {row.clipId ? "Clip attached" : "No clip attached"}</div></div></div><div className="flex flex-col items-end gap-2"><span className={`rounded-full border px-2 py-1 text-[9px] font-semibold ${row.status === "PUBLISHED" ? "border-emerald-300/20 text-emerald-200" : row.status === "FAILED" ? "border-red-300/20 text-red-200" : "border-white/10 text-zinc-400"}`}>{row.status.toLowerCase()}</span>{["SCHEDULED", "PUBLISHING"].includes(row.status) && <CancelButton id={row.id}/>}</div></article>; })}</div></div>}
  </WorkspaceFrame>;
}
