import Link from "next/link";
import { requireUser } from "../../lib/auth";
import { db } from "../../lib/db";
import CancelButton from "./CancelButton";

export default async function CalendarPage() {
  const user = await requireUser();
  const rows = await db.scheduledPost.findMany({ where: { userId: user.id }, orderBy: { scheduledFor: "asc" }, include: { clip: true, socialConnection: true } });
  return <main className="min-h-screen"><header className="border-b border-white/[.07]"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/dashboard" className="text-xs text-[#9ca6b4] hover:text-white">← Workspace</Link><Link href="/settings" className="cf-button cf-button-secondary min-h-9 text-[10px]">Publishing accounts</Link></div></header><section className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><p className="cf-eyebrow">Publishing planner</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.06em]">Calendar</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#8792a1]">Review scheduled posts and their real provider status. Scheduling requires a configured publishing connection.</p>{rows.length===0?<div className="cf-panel mt-8 rounded-2xl p-8 sm:p-12"><span className="grid h-11 w-11 place-items-center rounded-xl bg-white/[.04] text-xl text-[#c4f56b]">▦</span><h2 className="mt-5 text-xl font-semibold">Your calendar is clear.</h2><p className="mt-2 max-w-lg text-sm leading-6 text-[#8792a1]">No scheduled posts are stored yet. Connect a publishing account before scheduling posts; this page won't display fictional entries.</p><Link href="/settings" className="cf-button cf-button-secondary mt-5">Connect an account</Link></div>:<div className="mt-8 space-y-2">{rows.map(post=><article key={post.id} className="cf-panel flex flex-col gap-4 rounded-2xl p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/[.08] bg-white/[.03] text-[#c4f56b]">▦</span><div><p className="text-xs font-semibold">{post.clip?.title ?? post.clip?.category ?? "Scheduled post"}</p><p className="mt-1 text-[10px] text-[#8792a1]">{post.scheduledFor.toLocaleString()} · {post.socialConnection?.provider ?? "No provider connected"}</p><p className="mt-2 text-[9px] text-[#687383]">Status: {post.status}</p>{post.error&&<p className="mt-2 text-[10px] text-rose-300">{post.error}</p>}</div></div>{["SCHEDULED","PUBLISHING"].includes(post.status)&&<CancelButton id={post.id}/>}</article>)}</div>}</section></main>;
}
