import { requireUser } from "../../lib/auth";
import { db } from "../../lib/db";
import BillingActions from "./BillingActions";
import WorkspaceFrame from "../../components/WorkspaceFrame";

function pretty(value: number) { return Math.max(0, Math.round(value)).toLocaleString("en-IN"); }

export default async function Usage() {
  const user = await requireUser();
  const [usage, subscription] = await Promise.all([db.usage.findUnique({ where: { userId: user.id } }), db.subscription.findUnique({ where: { userId: user.id } })]);
  const plan = subscription?.plan ?? "free";
  const metrics = [{ label: "Minutes analyzed", value: pretty(usage?.minutesAnalyzed ?? 0), icon: "◷", note: "Source duration processed" }, { label: "Renders", value: pretty(usage?.renders ?? 0), icon: "▷", note: "Render jobs recorded" }, { label: "Exports", value: pretty(usage?.exports ?? 0), icon: "↗", note: "Export records created" }];
  return <WorkspaceFrame active="/usage" email={user.email} eyebrow="Account & billing" title="Plan and usage" description="Review the usage records and manage your billing portal." action={<span className="rounded-full border border-[#c4f36b]/20 bg-[#c4f36b]/[.06] px-3 py-1.5 text-xs font-semibold capitalize text-[#d7f9a7]">{plan} plan</span>}>
    <section className="overflow-hidden rounded-2xl border border-white/[.08] bg-[#10141a]"><div className="flex flex-col justify-between gap-4 border-b border-white/[.07] p-5 sm:flex-row sm:items-center sm:p-6"><div><div className="text-xs text-zinc-500">Current subscription</div><h2 className="mt-2 text-2xl font-semibold capitalize">{plan} plan</h2><p className="mt-1 text-xs text-zinc-500">{subscription?.stripeCustomerId ? "Billing account linked" : "No billing customer is linked yet"}</p></div><div className="rounded-xl border border-white/[.07] bg-white/[.02] px-4 py-3"><div className="text-[9px] uppercase tracking-[.15em] text-zinc-600">Account</div><div className="mt-1 text-xs">{user.email}</div></div></div><div className="grid gap-px bg-white/[.06] sm:grid-cols-3">{metrics.map(metric=><div key={metric.label} className="bg-[#10141a] p-5 sm:p-6"><div className="flex items-center justify-between"><span className="text-xs text-zinc-500">{metric.label}</span><span className="text-[#c4f36b]">{metric.icon}</span></div><div className="mt-4 text-3xl font-semibold tracking-tight">{metric.value}</div><p className="mt-2 text-[10px] text-zinc-600">{metric.note}</p></div>)}</div></section>
    <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_320px]"><section className="rounded-2xl border border-white/[.08] bg-[#10141a] p-5 sm:p-6"><h2 className="font-semibold">Usage details</h2><p className="mt-2 text-sm leading-6 text-zinc-500">These figures come from your persisted account usage row. Limits depend on the plan configuration and are not estimated here.</p><div className="mt-5 space-y-3">{metrics.map(metric=><div key={metric.label} className="flex items-center justify-between border-b border-white/[.06] pb-3 last:border-0 last:pb-0"><span className="text-xs text-zinc-400">{metric.label}</span><span className="font-mono text-sm">{metric.value}</span></div>)}</div></section><aside className="rounded-2xl border border-white/[.08] bg-[#10141a] p-5 sm:p-6"><div className="text-xs font-semibold">Billing actions</div><p className="mt-2 text-xs leading-5 text-zinc-500">Open the secure billing portal or start checkout if your account has the required billing configuration.</p><div className="mt-4"><BillingActions hasCustomer={Boolean(subscription?.stripeCustomerId)}/></div></aside></div>
  </WorkspaceFrame>;
}
