import Link from "next/link";
import { requireUser } from "../../lib/auth";
import { db } from "../../lib/db";
import BillingActions from "./BillingActions";

export default async function UsagePage() {
  const user = await requireUser();
  const [usage, subscription] = await Promise.all([db.usage.findUnique({ where: { userId: user.id } }), db.subscription.findUnique({ where: { userId: user.id } })]);
  const metrics = [{ label: "Current plan", value: subscription?.plan ?? "free", note: subscription?.status ?? "active" }, { label: "Minutes analyzed", value: String(Math.round(usage?.minutesAnalyzed ?? 0)), note: "Recorded source processing" }, { label: "Renders created", value: String(usage?.renders ?? 0), note: "Persisted render count" }, { label: "Exports created", value: String(usage?.exports ?? 0), note: "Recorded export count" }];
  return <main className="min-h-screen"><header className="border-b border-white/[.07]"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/dashboard" className="text-xs text-[#9ca6b4] hover:text-white">← Workspace</Link><span className="text-[10px] text-[#687383]">ACCOUNT & BILLING</span></div></header><section className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><p className="cf-eyebrow">Account overview</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.06em]">Usage & plan</h1><p className="mt-3 text-sm leading-6 text-[#8792a1]">Your current plan and usage recorded by Clip Finder. Values are based on persisted account data.</p><div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(m=><article key={m.label} className="cf-panel rounded-2xl p-5"><p className="text-[11px] text-[#8792a1]">{m.label}</p><p className="mt-4 text-2xl font-semibold capitalize">{m.value}</p><p className="mt-2 text-[10px] text-[#687383]">{m.note}</p></article>)}</div><section className="cf-panel mt-6 rounded-2xl p-5 sm:p-7"><p className="cf-eyebrow">Subscription management</p><h2 className="mt-2 text-lg font-semibold">Manage your plan</h2><p className="mt-2 text-xs leading-6 text-[#8792a1]">Billing actions depend on your configured payment provider and subscription state. No payment status is inferred from usage.</p><BillingActions hasCustomer={Boolean(subscription?.stripeCustomerId)} /></section></section></main>;
}
