import Link from "next/link";
import { requireUser } from "../../lib/auth";
import { db } from "../../lib/db";

function fmt(d: Date) { return d.toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }); }
function statusTone(status: string) {
  if (status === "READY") return "border-emerald-400/20 bg-emerald-400/[.08] text-emerald-300";
  if (status === "FAILED") return "border-red-400/20 bg-red-400/[.08] text-red-300";
  if (["QUEUED", "DOWNLOADING", "INGESTING", "TRANSCRIBING", "ANALYZING", "RENDERING", "EDITING"].includes(status)) return "border-[#c4f36b]/20 bg-[#c4f36b]/[.07] text-[#d7f9a7]";
  return "border-white/10 bg-white/[.04] text-zinc-400";
}
const nav = [{ href: "/dashboard", label: "Overview", icon: "◫" }, { href: "/search", label: "Search", icon: "⌕" }, { href: "/favorites", label: "Favorites", icon: "♡" }, { href: "/exports", label: "Exports", icon: "↗" }, { href: "/analytics", label: "Analytics", icon: "⌁" }, { href: "/calendar", label: "Calendar", icon: "▦" }, { href: "/templates", label: "Templates", icon: "▤" }, { href: "/usage", label: "Plan & usage", icon: "◉" }, { href: "/settings", label: "Connections", icon: "⚙" }, { href: "/profile", label: "Profile", icon: "◎" }];

export default async function DashboardPage() {
  const u = await requireUser();
  const projects = await db.project.findMany({ where: { userId: u.id }, orderBy: { updatedAt: "desc" }, include: { source: true, clips: { orderBy: { score: "desc" }, take: 1 }, jobs: { orderBy: { createdAt: "desc" }, take: 1 } } });
  const [usage, totalClips] = await Promise.all([db.usage.findUnique({ where: { userId: u.id } }), db.clip.count({ where: { project: { userId: u.id } } })]);
  return <main className="min-h-screen bg-[#080a0d] text-white">
    <aside className="fixed inset-y-0 left-0 z-20 hidden w-[248px] flex-col border-r border-white/[.07] bg-[#0b0f14] px-4 py-5 lg:flex">
      <Link href="/" className="mb-9 flex items-center gap-2.5 px-2 font-semibold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-[10px] bg-[#c4f36b] text-[#12180a]">▶</span><span>clip<span className="text-[#c4f36b]">finder</span><span className="ml-1 text-[10px] text-zinc-600">2.0</span></span></Link>
      <div className="px-3 pb-3 text-[10px] font-bold tracking-[.18em] text-zinc-600">WORKSPACE</div><nav className="space-y-1" aria-label="Workspace">{nav.slice(0, 5).map(n => <Link key={n.href} href={n.href} aria-current={n.href === "/dashboard" ? "page" : undefined} className="cf-sidebar-link"><span className="w-5 text-center text-base">{n.icon}</span>{n.label}</Link>)}</nav>
      <div className="mt-8 px-3 pb-3 text-[10px] font-bold tracking-[.18em] text-zinc-600">MANAGE</div><nav className="space-y-1">{nav.slice(5).map(n => <Link key={n.href} href={n.href} className="cf-sidebar-link"><span className="w-5 text-center text-base">{n.icon}</span>{n.label}</Link>)}</nav>
      <div className="mt-auto rounded-2xl border border-white/[.08] bg-white/[.025] p-4"><div className="text-xs font-semibold">Need a new cut?</div><p className="mt-1.5 text-[11px] leading-5 text-zinc-500">Start with a source you have permission to use.</p><Link href="/project/new" className="cf-button mt-3 w-full !min-h-10 !text-xs">New project ↗</Link></div>
      <div className="mt-4 flex items-center gap-3 border-t border-white/[.07] px-2 pt-4"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#1d2930] text-sm font-semibold text-[#c4f36b]">{(u.email?.[0] ?? "C").toUpperCase()}</div><div className="min-w-0"><div className="truncate text-xs font-medium">{u.email}</div><div className="mt-1 text-[10px] text-zinc-600">Creator account</div></div></div>
    </aside>
    <div className="min-h-screen lg:pl-[248px]"><header className="flex items-center justify-between border-b border-white/[.07] px-5 py-4 md:px-8"><div className="lg:hidden"><Link href="/" className="font-semibold">clip<span className="text-[#c4f36b]">finder</span></Link></div><div className="hidden text-xs text-zinc-500 lg:block">Workspace <span className="mx-2 text-zinc-700">/</span><span className="text-zinc-300">Overview</span></div><div className="flex items-center gap-2"><Link href="/search" className="cf-button-secondary !min-h-9 !rounded-[10px] !px-3 text-xs">⌕ <span className="hidden sm:inline">Search</span></Link><Link href="/project/new" className="cf-button !min-h-9 !rounded-[10px] !px-3 text-xs">＋ New project</Link></div></header>
      <nav aria-label="Mobile workspace navigation" className="flex gap-1 overflow-x-auto border-b border-white/[.06] px-3 py-2 lg:hidden">{nav.map(n => <Link key={n.href} href={n.href} aria-current={n.href === "/dashboard" ? "page" : undefined} className={`shrink-0 rounded-lg px-3 py-2 text-[10px] font-medium ${n.href === "/dashboard" ? "bg-[#c4f36b]/[.08] text-[#d7f9a7]" : "text-zinc-500 hover:bg-white/[.04] hover:text-zinc-200"}`}>{n.label}</Link>)}</nav>
      <div className="mx-auto max-w-[1440px] px-5 py-8 md:px-8 md:py-10">
        <div className="cf-enter flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="cf-kicker">Creator overview</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.045em] sm:text-4xl">Your workspace<span className="text-[#c4f36b]">.</span></h1><p className="mt-2 text-sm text-zinc-500">The right moment changes everything. Let's find yours.</p></div><div className="text-xs text-zinc-600">Signed in as <span className="text-zinc-300">{u.email}</span></div></div>
        <section className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Workspace statistics">
          {[{label:"Total projects",value:projects.length,sub:"Sources in your workspace",symbol:"◫"},{label:"Clips discovered",value:totalClips,sub:"Analyzed moments across your projects",symbol:"▶"},{label:"Minutes analyzed",value:Math.round(usage?.minutesAnalyzed??0),sub:"Source processing usage",symbol:"◷"},{label:"Exports completed",value:usage?.exports??0,sub:"Delivered from your projects",symbol:"↗"}].map((s,i)=><div key={s.label} className="cf-card cf-enter p-5" style={{animationDelay:`${i*60}ms`}}><div className="flex items-center justify-between"><span className="text-xs text-zinc-500">{s.label}</span><span className="grid h-8 w-8 place-items-center rounded-lg border border-white/[.07] bg-white/[.025] text-[#c4f36b]">{s.symbol}</span></div><div className="mt-5 text-3xl font-semibold tracking-tight">{s.value}</div><div className="mt-1.5 text-[11px] text-zinc-600">{s.sub}</div></div>)}
        </section>
        <section className="mt-10">
          <div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-semibold">Recent projects</h2><p className="mt-1 text-xs text-zinc-500">Pick up where you left off.</p></div><div className="flex items-center gap-3"><span className="text-xs text-zinc-600">{ready} ready</span><Link href="/exports" className="text-xs text-zinc-400 transition hover:text-[#c4f36b]">View exports →</Link></div></div>
          {projects.length === 0 ? <div className="cf-card relative overflow-hidden p-7 sm:p-12"><div className="pointer-events-none absolute -right-20 -top-20 h-64 w-64 rounded-full bg-[#c4f36b]/[.06] blur-3xl"/><div className="relative mx-auto max-w-lg text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-[#c4f36b]/20 bg-[#c4f36b]/[.07] text-2xl text-[#c4f36b]">▶</div><h3 className="mt-5 text-xl font-semibold">Start with your first source</h3><p className="mt-2 text-sm leading-6 text-zinc-500">Paste a supported video URL or upload media. Clip Finder will create a project and hand it to the processing pipeline.</p><Link href="/project/new" className="cf-button mt-6">Create your first project ↗</Link><p className="mt-4 text-[11px] text-zinc-600">Only process media you have rights or permission to use.</p></div></div> : <div className="grid gap-3 md:grid-cols-2 2xl:grid-cols-3">{projects.map((p,i)=>{const j=p.jobs[0];const status=j?.status??"READY";return <Link key={p.id} href={"/project/"+p.id} className="cf-card group cf-enter p-5 transition duration-200 hover:-translate-y-0.5 hover:border-white/20" style={{animationDelay:`${i*45}ms`}}><div className="flex items-start justify-between gap-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/[.08] bg-white/[.035] text-[#c4f36b]">▶</div><span className={`rounded-full border px-2.5 py-1 text-[10px] font-medium ${statusTone(status)}`}>{status.replaceAll("_"," ")}</span></div><h3 className="mt-5 truncate text-base font-semibold transition group-hover:text-[#d7f9a7]">{p.name}</h3><p className="mt-1 truncate text-xs text-zinc-600">{p.source?.url??"Uploaded source"}</p><div className="mt-6 flex items-end justify-between border-t border-white/[.07] pt-4"><div><div className="text-[10px] uppercase tracking-wider text-zinc-600">Top clip score</div><div className="mt-1 text-xl font-semibold">{p.clips[0]?.score?.toFixed(0)??"—"}<span className="ml-1 text-xs font-normal text-zinc-600">/ 100</span></div></div><div className="text-right"><div className="text-[10px] text-zinc-600">Updated</div><div className="mt-1 text-xs text-zinc-400">{fmt(p.updatedAt)}</div></div></div><div className="mt-4 h-1 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-[#c4f36b]/80" style={{width:`${Math.min(100,Math.max(0,p.clips[0]?.score??0))}%`}}/></div></Link>})}</div>}
        </section>
        <footer className="mt-12 flex flex-col justify-between gap-2 border-t border-white/[.06] pt-5 text-[11px] text-zinc-600 sm:flex-row"><span>Clip Finder 2.0 · Your work, in progress.</span><span>Keep your source rights in mind.</span></footer>
      </div>
    </div>
  </main>;
}
