"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Segment={startS:number;endS:number};
type Clip={id:string;startS:number;endS:number;score:number|null;category:string|null;title:string|null;status:string;edit?:{aspectRatio:string;segments:Segment[];version:number}|null};
type Props={projectId:string;mediaId:string|null;duration:number;clips:Clip[]};

const fmt=(s:number)=>{const m=Math.floor(s/60),sec=Math.floor(s%60),ms=Math.floor((s%1)*10);return `${m.toString().padStart(2,"0")}:${sec.toString().padStart(2,"0")}.${ms}`};

export default function Editor({projectId,mediaId,duration,clips}:{projectId:string;mediaId:string|null;duration:number;clips:Clip[]}){
 const video=useRef<HTMLVideoElement>(null); const [selected,setSelected]=useState<Clip|null>(clips[0]??null);
 const [segments,setSegments]=useState<Segment[]>(clips[0]?.edit?.segments??(clips[0]?[{startS:clips[0].startS,endS:clips[0].endS}]:[]));
 const [aspect,setAspect]=useState(clips[0]?.edit?.aspectRatio??"9:16"); const [time,setTime]=useState(0);
 const [playing,setPlaying]=useState(false); const [saving,setSaving]=useState(false); const [rendering,setRendering]=useState(false); const [message,setMessage]=useState("");
 const [history,setHistory]=useState<Segment[][]>([]); const [future,setFuture]=useState<Segment[][]>([]);
 const current=segments[0];

 useEffect(()=>{if(!selected)return;setSegments(selected.edit?.segments??[{startS:selected.startS,endS:selected.endS}]);setAspect(selected.edit?.aspectRatio??"9:16");setMessage("")},[selected?.id]);
 useEffect(()=>{const v=video.current;if(!v)return;const on=()=>setTime(v.currentTime);v.addEventListener("timeupdate",on);return()=>v.removeEventListener("timeupdate",on)},[]);
 const push=(next:Segment[])=>{setHistory(h=>[...h,segments]);setFuture([]);setSegments(next)};
 const seek=(t:number)=>{if(video.current){video.currentTime=Math.max(0,Math.min(duration,t));setTime(Math.max(0,Math.min(duration,t)))}};
 const split=()=>{if(!current)return;const cut=Math.max(current.startS+0.1,Math.min(current.endS-0.1,time));if(cut<=current.startS||cut>=current.endS)return;push([...segments.slice(0,0),{startS:current.startS,endS:cut},{startS:cut,endS:current.endS},...segments.slice(1)])};
 const trimIn=()=>{if(!current)return;const next={...current,startS:Math.min(time,current.endS-0.1)};push([next,...segments.slice(1)])};
 const trimOut=()=>{if(!current)return;const next={...current,endS:Math.max(time,current.startS+0.1)};push([next,...segments.slice(1)])};
 const remove=()=>{if(!segments.length)return;push(segments.slice(1));};
 const undo=()=>{const prev=history.at(-1);if(!prev)return;setFuture(f=>[segments,...f]);setSegments(prev);setHistory(h=>h.slice(0,-1))};
 const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h,segments]);setSegments(next);setFuture(f=>f.slice(1))};
 useEffect(()=>{const on=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.tagName==="INPUT")return;if(e.key===" "){e.preventDefault();video.current?.paused?video.current?.play():video.current?.pause();setPlaying(!!video.current&&!video.current.paused)}if(e.key==="i")trimIn();if(e.key==="o")trimOut();if(e.key==="s")split();if(e.key==="Delete")remove();if((e.ctrlKey||e.metaKey)&&e.key==="z"){e.preventDefault();undo()}if((e.ctrlKey||e.metaKey)&&e.key==="y"){e.preventDefault();redo()}};window.addEventListener("keydown",on);return()=>window.removeEventListener("keydown",on)});
 const save=useCallback(async()=>{if(!selected||!segments.length)return;setSaving(true);setMessage("");try{const first=segments[0];const r=await fetch(`/api/clips/${selected.id}/edit`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({startS:first.startS,endS:first.endS,segments,aspectRatio:aspect})});const d=await r.json();if(!r.ok)throw new Error(d.error??"Save failed");setSelected(c=>c?{...c,edit:d}:c);setMessage("Saved")}catch(e){setMessage(e instanceof Error?e.message:"Save failed")}finally{setSaving(false)}},[selected,segments,aspect]);
 useEffect(()=>{if(!selected||!segments.length)return;const t=setTimeout(save,700);return()=>clearTimeout(t)},[segments,aspect]);
 const render=async()=>{if(!selected){return}await save();setRendering(true);setMessage("");try{const r=await fetch(`/api/clips/${selected.id}/render`,{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error??"Render failed");setMessage("Render queued — the worker will process it.");}catch(e){setMessage(e instanceof Error?e.message:"Render failed")}finally{setRendering(false)}};
 const pct=(t:number)=>duration?Math.min(100,t/duration*100):0;
 return <div className="grid min-h-[760px] grid-cols-[260px_1fr_300px] overflow-hidden rounded-3xl border border-white/10 bg-[#0d0f0b]">
   <aside className="border-r border-white/10 p-4"><div className="mb-4 text-xs uppercase tracking-[.2em] text-zinc-500">Clips</div>{clips.map(c=><button key={c.id} onClick={()=>setSelected(c)} className={`mb-2 w-full rounded-xl border p-3 text-left ${selected?.id===c.id?"border-lime-300/60 bg-lime-300/10":"border-white/10 bg-white/[.02]"}`}><div className="flex justify-between"><span className="font-medium">{c.category??"AI Detect"}</span><span className="text-xs text-zinc-500">{c.score?.toFixed(0)??"—"}</span></div><div className="mt-1 text-xs text-zinc-500">{fmt(c.startS)} → {fmt(c.endS)}</div></button>)}</aside>
   <section className="flex min-w-0 flex-col"><div className="flex items-center justify-between border-b border-white/10 px-5 py-3"><div><span className="text-sm font-semibold">Editor</span>{selected&&<span className="ml-3 text-xs text-zinc-500">{selected.status}</span>}</div><div className="flex gap-2"><button onClick={undo} disabled={!history.length} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs disabled:opacity-30">Undo</button><button onClick={redo} disabled={!future.length} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs disabled:opacity-30">Redo</button></div></div>
   <div className="relative flex flex-1 items-center justify-center bg-black p-6"><div className={`relative h-full max-h-[540px] w-full max-w-[760px] overflow-hidden rounded-2xl bg-zinc-950 ${aspect==="9:16"?"max-w-[390px]":aspect==="1:1"?"max-w-[540px]":""}`}><video ref={video} src={mediaId?`/api/media/${mediaId}`:undefined} controls={false} className="h-full w-full object-contain" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onClick={()=>{video.current?.paused?video.current?.play():video.current?.pause()}}/><button onClick={()=>{video.current?.paused?video.current?.play():video.current?.pause()}} className="absolute bottom-4 left-4 rounded-full bg-black/70 px-4 py-2 text-xs">{playing?"Pause":"Play"}</button></div></div>
   <div className="border-t border-white/10 p-5"><div className="mb-3 flex items-center justify-between text-xs text-zinc-400"><span>{fmt(time)}</span><span>{fmt(duration)}</span></div><div className="relative h-14 cursor-pointer rounded-xl bg-white/[.04]" onClick={e=>{const r=e.currentTarget.getBoundingClientRect();seek((e.clientX-r.left)/r.width*duration)}}><div className="absolute inset-y-2 rounded-lg bg-white/10" style={{left:`${pct(current?.startS??0)}%`,right:`${100-pct(current?.endS??duration)}%`}}/><div className="absolute inset-y-0 w-0.5 bg-lime-300" style={{left:`${pct(time)}%`}}/></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={trimIn} className="tool">Trim in</button><button onClick={trimOut} className="tool">Trim out</button><button onClick={split} className="tool">Split</button><button onClick={remove} className="tool">Delete segment</button><button onClick={()=>seek(current?.startS??0)} className="tool">Go to start</button></div><div className="mt-3 text-xs text-zinc-500">Space play · I trim in · O trim out · S split · Delete remove · Ctrl/Cmd+Z undo</div></div></section>
   <aside className="border-l border-white/10 p-5"><div className="text-xs uppercase tracking-[.2em] text-zinc-500">Inspector</div><div className="mt-6"><label className="text-sm text-zinc-400">Aspect ratio</label><div className="mt-2 grid grid-cols-3 gap-2">{["9:16","1:1","16:9"].map(a=><button key={a} onClick={()=>setAspect(a)} className={`rounded-xl border py-3 text-xs ${aspect===a?"border-lime-300 bg-lime-300/10 text-lime-200":"border-white/10"}`}>{a}</button>)}</div></div><div className="mt-8"><div className="text-sm text-zinc-400">Segments</div>{segments.map((s,i)=><div key={i} className="mt-2 rounded-xl bg-white/[.04] p-3 text-xs">{i+1}. {fmt(s.startS)} → {fmt(s.endS)}</div>)}</div><div className="mt-8 rounded-2xl border border-white/10 bg-white/[.03] p-4"><div className="text-sm font-medium">Render</div><p className="mt-1 text-xs text-zinc-500">FFmpeg will render the saved edit asynchronously.</p><button disabled={!selected||saving||rendering} onClick={render} className="mt-4 w-full rounded-xl bg-lime-300 px-4 py-3 text-sm font-semibold text-black disabled:opacity-40">{rendering?"Queueing…":"Render clip"}</button></div>{message&&<p className="mt-4 text-xs text-zinc-400">{message}</p>}</aside>
 </div>
}
