import { requireUser } from "../../lib/auth";
import WorkspaceFrame from "../../components/WorkspaceFrame";

export default async function Profile() {
  const user = await requireUser();
  const initial = (user.name || user.email || "C").trim().slice(0, 1).toUpperCase();
  return <WorkspaceFrame active="/profile" email={user.email} eyebrow="Your account" title="Profile" description="A quick look at the account attached to your creator workspace.">
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_320px]"><section className="overflow-hidden rounded-2xl border border-white/[.08] bg-[#10141a]"><div className="h-28 bg-[radial-gradient(ellipse_at_20%_0%,rgba(196,243,107,.18),transparent_55%),linear-gradient(115deg,#141c20,#11141a)]"/><div className="px-5 pb-6 sm:px-7"><div className="-mt-8 grid h-16 w-16 place-items-center rounded-2xl border-4 border-[#10141a] bg-[#c4f36b] text-2xl font-bold text-[#14190d]">{initial}</div><h2 className="mt-4 text-xl font-semibold">{user.name || "Creator account"}</h2><p className="mt-1 text-sm text-zinc-500">{user.email}</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-white/[.07] bg-white/[.015] p-4"><div className="text-[10px] font-semibold uppercase tracking-[.15em] text-zinc-600">Display name</div><div className="mt-2 text-sm">{user.name || "Not set"}</div></div><div className="rounded-xl border border-white/[.07] bg-white/[.015] p-4"><div className="text-[10px] font-semibold uppercase tracking-[.15em] text-zinc-600">Email address</div><div className="mt-2 break-all text-sm">{user.email}</div></div></div><p className="mt-5 text-xs leading-5 text-zinc-600">Profile editing is not exposed yet. This screen shows the account data currently stored by Clip Finder rather than unsaved mock fields.</p></div></section><aside className="space-y-3"><div className="rounded-2xl border border-white/[.08] bg-[#10141a] p-5"><div className="text-xs font-semibold">Account shortcuts</div><a href="/settings" className="mt-4 flex items-center justify-between border-b border-white/[.06] py-3 text-xs text-zinc-300 hover:text-white"><span>Connected accounts</span><span>↗</span></a><a href="/usage" className="flex items-center justify-between border-b border-white/[.06] py-3 text-xs text-zinc-300 hover:text-white"><span>Plan and usage</span><span>↗</span></a><a href="/dashboard" className="flex items-center justify-between py-3 text-xs text-zinc-300 hover:text-white"><span>My projects</span><span>↗</span></a></div><div className="rounded-2xl border border-white/[.08] bg-[#10141a] p-5"><div className="text-xs font-semibold">Privacy by design</div><p className="mt-2 text-xs leading-5 text-zinc-500">Your workspace is scoped to your signed-in account. Only process media you have permission to use.</p></div></aside></div>
  </WorkspaceFrame>;
}
