import Link from "next/link";
import { requireUser } from "../../lib/auth";
import { db } from "../../lib/db";
import SyncButton from "./SyncButton";

export default async function AnalyticsPage() {
  const user = await requireUser();
  const rows = await db.analyticsRecord.findMany({ where: { userId: user.id }, orderBy: { recordedAt: "desc" }, take: 100 });
  const sum = (key: "views" | "likes" | "comments" | "shares") => rows.reduce((total, row) => total + row[key], 0);
  const metrics = [{ label: "Views", value: sum("views") }, { label: "Likes", value: sum("likes") }, { label: "Comments", value: sum("comments") }, { label: "Shares", value: sum("shares") }];
  return <main className="min-h-screen"><header className="border-b border-white/[.07]"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/dashboard" className="text-xs text-[#9ca6b4] hover:text-white">← Workspace</Link><SyncButton /></div></header><section className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><p className="cf-eyebrow">Performance signals</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.06em]">Analytics</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#8792a1]">Performance metrics recorded from connected publishing providers. We never invent views or engagement data.</p>{rows.length===0?<div className="cf-panel mt-8 rounded-2xl p-8 sm:p-12"><span className="grid h-11 w-11 place-items-center rounded-xl bg-white/[.04] text-xl text-[#c4f56b]">↗</span><h2 className="mt-5 text-xl font-semibold">No platform analytics yet.</h2><p className="mt-2 max-w-lg text-sm leading-6 text-[#8792a1]">This area will populate after a real publishing integration reports performance and records it to your account.</p><Link href="/settings" className="cf-button cf-button-secondary mt-5">Review connected accounts</Link></div>:<><div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(m=><article key={m.label} className="cf-panel rounded-2xl p-5"><p className="text-[11px] text-[#8792a1]">{m.label}</p><p className="mt-4 text-3xl font-semibold">{m.value.toLocaleString()}</p><p className="mt-2 text-[10px] text-[#687383]">Recorded total</p></article>)}</div><div className="mt-8 space-y-2">{rows.map(row=><article key={row.id} className="cf-panel flex flex-wrap items-center justify-between gap-3 rounded-xl p-4"><div><p className="text-xs font-semibold">{row.platform} · {row.postId}</p><p className="mt-1 text-[10px] text-[#687383]">{row.recordedAt.toLocaleString()}</p></div><div className="flex gap-4 text-[10px] text-[#9ca6b4]"><span>{row.views} views</span><span>{row.likes} likes</span><span>{row.comments} comments</span><span>{row.shares} shares</span></div></article>)}</div></>}</section></main>;
}
