import Link from "next/link";
import { requireUser } from "../../lib/auth";
import { db } from "../../lib/db";
import SyncButton from "./SyncButton";

export default async function Analytics() {
  const user = await requireUser();
  const rows = await db.analyticsRecord.findMany({ where: { userId: user.id }, orderBy: { recordedAt: "desc" }, take: 100 });
  const sum = (key: keyof typeof rows[number]) => rows.reduce((total, row) => total + Number(row[key] ?? 0), 0);
  const metrics = [{ label: "Views", value: sum("views") }, { label: "Likes", value: sum("likes") }, { label: "Comments", value: sum("comments") }, { label: "Shares", value: sum("shares") }];
  return <main className="min-h-screen bg-[#080a0d] px-5 pb-12 text-white sm:px-8"><header className="mx-auto flex max-w-6xl items-center justify-between border-b border-white/[.07] py-5"><Link href="/dashboard" className="text-sm text-zinc-400 hover:text-white">← Workspace</Link><Link href="/" className="font-semibold">clip<span className="text-[#c4f36b]">finder</span></Link></header><div className="mx-auto max-w-6xl pt-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="cf-kicker">Performance</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Analytics<span className="text-[#c4f36b]">.</span></h1><p className="mt-2 text-sm text-zinc-500">Only platform-reported metrics appear here.</p></div><SyncButton/></div>{rows.length===0?<div className="cf-card mt-8 px-6 py-14 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl border border-white/10 text-xl text-[#c4f36b]">⌁</div><h2 className="mt-4 text-lg font-semibold">No performance data yet</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-zinc-500">Connect a supported publishing account and sync real analytics after posts have been published. We won't fabricate view counts.</p><Link href="/settings" className="cf-button mt-5">Manage connections</Link></div>:<><div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(m=><div key={m.label} className="cf-card p-5"><div className="text-xs text-zinc-500">{m.label}</div><div className="mt-4 text-3xl font-semibold tracking-tight">{m.value.toLocaleString("en-IN")}</div></div>)}</div><div className="cf-card mt-5 overflow-hidden"><div className="border-b border-white/[.07] p-5"><h2 className="font-semibold">Recent platform records</h2></div><div className="divide-y divide-white/[.06]">{rows.map(r=><div key={r.id} className="flex flex-col justify-between gap-2 px-5 py-4 sm:flex-row sm:items-center"><div><div className="text-sm font-medium">{r.platform} · {r.externalPostId}</div><div className="mt-1 text-xs text-zinc-600">{r.recordedAt.toLocaleString("en-IN")}</div></div><div className="flex gap-4 text-xs text-zinc-400"><span>{r.views} views</span><span>{r.likes} likes</span><span>{r.shares} shares</span></div></div>)}</div></div></>}</div></main>;
}