import Link from "next/link";
import { requireUser } from "../../lib/auth";
import { db } from "../../lib/db";
import WorkspaceFrame from "../../components/WorkspaceFrame";

export default async function Favorites() {
  const user = await requireUser();
  const rows = await db.favorite.findMany({ where: { userId: user.id, clipId: { not: null } }, orderBy: { createdAt: "desc" }, include: { clip: true, project: true } });
  return <WorkspaceFrame active="/favorites" email={user.email} eyebrow="Saved moments" title="Favorites" description="Your shortlist of clips worth coming back to." action={<span className="rounded-lg border border-white/[.08] bg-white/[.025] px-3 py-2 text-xs text-zinc-400">{rows.length} saved</span>}>
    {rows.length === 0 ? <div className="rounded-2xl border border-dashed border-white/[.12] bg-white/[.012] px-6 py-16 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl border border-white/[.08] text-xl text-[#c4f36b]">♡</div><h2 className="mt-4 text-lg font-semibold">Your shortlist starts here</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-zinc-500">Favorite a real clip from Studio to save it here for quick access.</p><Link href="/dashboard" className="cf-button mt-5">Browse projects ↗</Link></div> : <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{rows.map((row,index)=><Link key={row.id} href={`/project/${row.projectId}`} className="group overflow-hidden rounded-2xl border border-white/[.08] bg-[#10141a] transition hover:-translate-y-0.5 hover:border-[#c4f36b]/25"><div className={`relative h-28 bg-gradient-to-br ${index%3===0?"from-[#c4f36b]/15 to-transparent":index%3===1?"from-[#8bb7ff]/15 to-transparent":"from-[#f4a6d7]/15 to-transparent"}`}><span className="absolute left-4 top-4 rounded-md border border-white/10 bg-black/25 px-2 py-1 text-[9px] uppercase tracking-wider text-zinc-300">Saved clip</span><span className="absolute right-4 top-3 text-xl text-[#c4f36b]">♥</span></div><div className="p-5"><div className="truncate text-[10px] text-zinc-500">{row.project?.name ?? "Project"}</div><div className="mt-2 truncate text-sm font-semibold group-hover:text-[#d7f9a7]">{row.clip?.title ?? row.clip?.category ?? "Saved clip"}</div><div className="mt-2 font-mono text-[10px] text-zinc-500">{row.clip ? `${row.clip.startS.toFixed(1)}s → ${row.clip.endS.toFixed(1)}s` : "Clip unavailable"}</div><div className="mt-4 flex items-center justify-between border-t border-white/[.07] pt-3 text-[10px]"><span className="text-zinc-600">AI score <b className="ml-1 text-[#c4f36b]">{row.clip?.score?.toFixed(0) ?? "—"}</b></span><span className="text-zinc-400">Open editor →</span></div></div></Link>)}</div>}
  </WorkspaceFrame>;
}
