import Link from "next/link";
import { requireUser } from "../../../../lib/auth";
import { db } from "../../../../lib/db";
import TranscriptEditor from "./TranscriptEditor";
import LongFormRender from "./LongFormRender";

function stamp(value: unknown) {
  const seconds = Math.max(0, Number(value) || 0);
  return `${Math.floor(seconds / 60).toString().padStart(2, "0")}:${Math.floor(seconds % 60).toString().padStart(2, "0")}`;
}

export default async function LongFormPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireUser();
  const { id } = await params;
  const project = await db.project.findFirst({ where: { id, userId: user.id }, include: { longFormDocument: true, source: { include: { media: true } } } });
  if (!project) return <main className="min-h-screen bg-[#080a0d] p-6 text-white"><div className="mx-auto max-w-3xl rounded-2xl border border-white/[.08] bg-[#10141a] p-8"><h1 className="text-xl font-semibold">Project not found</h1><p className="mt-2 text-sm text-zinc-500">This project may have been removed or belongs to another account.</p><Link href="/dashboard" className="cf-button mt-5">Back to workspace</Link></div></main>;
  const document = project.longFormDocument;
  const asset = project.source?.media[0] ?? null;
  const chapters = Array.isArray(document?.chapters) ? document.chapters as Array<{ start?: number | string; title?: string }> : [];
  return <main className="min-h-screen bg-[#080a0d] text-white">
    <header className="sticky top-0 z-20 border-b border-white/[.07] bg-[#080a0d]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-3 px-4 py-4 sm:px-7"><Link href={`/project/${project.id}`} className="text-xs text-zinc-400 transition hover:text-white">← Back to clip editor</Link><Link href="/dashboard" className="font-semibold tracking-tight">clip<span className="text-[#c4f36b]">finder</span><span className="ml-1 text-[10px] text-zinc-600">STUDIO</span></Link><span className="rounded-lg border border-white/[.08] px-2.5 py-1.5 text-[10px] text-zinc-500">LONG-FORM</span></div></header>
    <div className="mx-auto max-w-[1500px] px-4 pb-12 sm:px-7">
      <div className="flex flex-col justify-between gap-4 border-b border-white/[.06] py-8 sm:flex-row sm:items-end"><div><p className="cf-kicker">Long-form workspace</p><h1 className="mt-3 max-w-4xl text-3xl font-semibold tracking-[-.045em] sm:text-4xl">{document?.title || project.name}</h1><p className="mt-2 text-sm text-zinc-500">Edit transcript copy, review chapter structure, and queue a full-length render.</p></div><span className="self-start rounded-full border border-white/[.08] bg-white/[.025] px-3 py-1.5 text-[10px] text-zinc-400 sm:self-auto">{document?.renderStatus?.toLowerCase() ?? "analysis pending"}</span></div>
      {!document ? <div className="mt-6 rounded-2xl border border-dashed border-white/[.12] bg-white/[.012] px-6 py-16 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl border border-white/[.08] text-xl text-[#c4f36b]">◷</div><h2 className="mt-4 text-lg font-semibold">Long-form analysis is still processing</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-zinc-500">The long-form document will appear after the analysis pipeline creates it. You can return to the project to check processing activity.</p><Link href={`/project/${project.id}`} className="cf-button mt-5">Back to project ↗</Link></div> : <div className="mt-6 grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_320px]">
        <div className="min-w-0 space-y-4">
          <section className="rounded-2xl border border-white/[.08] bg-[#10141a] p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">Overview & description</h2><p className="mt-1 text-xs text-zinc-600">Generated from the analyzed source.</p></div><span className="text-[10px] text-zinc-600">{chapters.length} chapters</span></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-zinc-400">{document.description || "No description was generated for this document."}</p></section>
          <section className="rounded-2xl border border-white/[.08] bg-[#10141a] p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">Chapter map</h2><p className="mt-1 text-xs text-zinc-600">Use these markers to understand the structure of the source.</p></div><span className="rounded-md bg-white/[.04] px-2 py-1 font-mono text-[10px] text-zinc-500">{String(chapters.length).padStart(2, "0")}</span></div>{chapters.length ? <div className="mt-5 space-y-2">{chapters.map((chapter, index) => <div key={index} className="flex gap-3 rounded-xl border border-white/[.05] bg-black/10 p-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-white/[.04] font-mono text-[10px] text-[#c4f36b]">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0 flex-1 self-center"><div className="text-xs font-medium">{chapter.title || `Chapter ${index + 1}`}</div></div><span className="self-center font-mono text-[10px] text-zinc-500">{stamp(chapter.start)}</span></div>)}</div> : <p className="mt-5 text-xs text-zinc-600">No chapters were returned for this document.</p>}</section>
          <TranscriptEditor projectId={project.id}/>
        </div>
        <aside className="space-y-4 xl:sticky xl:top-[84px]">
          <section className="rounded-2xl border border-white/[.08] bg-[#10141a] p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Source preview</h2><span className="text-[9px] uppercase tracking-wider text-zinc-600">Original</span></div>{asset ? <video src={`/api/media/${asset.id}`} controls playsInline className="mt-4 aspect-video w-full rounded-xl bg-black"/> : document.thumbnailKey ? <img src={`/api/media/thumbnail/${document.id}`} alt="Source thumbnail" className="mt-4 aspect-video w-full rounded-xl object-cover"/> : <div className="mt-4 grid aspect-video place-items-center rounded-xl border border-dashed border-white/[.1] text-xs text-zinc-600">No preview available</div>}<div className="mt-3 space-y-2 text-xs"><div className="flex justify-between gap-3"><span className="text-zinc-600">Project</span><span className="max-w-[180px] truncate text-zinc-300">{project.name}</span></div><div className="flex justify-between gap-3"><span className="text-zinc-600">Source duration</span><span className="text-zinc-300">{asset?.durationS ? stamp(asset.durationS) : "Unknown"}</span></div><div className="flex justify-between gap-3"><span className="text-zinc-600">Transcript lines</span><span className="text-zinc-300">Loaded in editor</span></div></div></section>
          <section className="rounded-2xl border border-white/[.08] bg-[#10141a] p-4"><h2 className="text-sm font-semibold">Render studio</h2><p className="mt-2 text-xs leading-5 text-zinc-500">Queue the long-form renderer. The server creates a job; the configured worker must process it before the final video is ready.</p><div className="mt-4"><LongFormRender projectId={project.id} initialStatus={document.renderStatus}/></div>{document.renderStatus === "READY" && <video src={`/api/projects/${project.id}/long-form/media`} controls playsInline className="mt-4 aspect-video w-full rounded-xl bg-black"/>}</section>
          <div className="rounded-xl border border-amber-300/15 bg-amber-300/[.025] p-4"><div className="text-xs font-semibold text-amber-100">Before publishing</div><p className="mt-2 text-[10px] leading-5 text-zinc-500">Review the final render and confirm that you have permission to use all source material.</p></div>
        </aside>
      </div>}
    </div>
  </main>;
}
