import {db} from "./lib/db";import {claimNextJob,finishJob,failJob} from "./lib/jobs";import path from "node:path";
const sleep=(n:number)=>new Promise(r=>setTimeout(r,n));const AI=process.env.AI_SERVICE_URL||"http://127.0.0.1:8000";
async function ai(pathname:string,body:unknown){const r=await fetch(AI+pathname,{method:"POST",headers:{"content-type":"application/json",...(process.env.AI_SERVICE_SECRET?{"x-ai-secret":process.env.AI_SERVICE_SECRET}:{})},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json()}
async function tick(){const j=await claimNextJob();if(!j)return;try{await db.job.update({where:{id:j.id},data:{progress:.02}});
 if(j.type==="PROJECT_READY"){await finishJob(j.id);return}
 if(j.type==="INGEST"){const p=j.payload as any;if(!p?.sourceUrl)throw new Error("Missing sourceUrl");const project=await db.project.findUniqueOrThrow({where:{id:j.projectId!}});const source=await db.source.findUniqueOrThrow({where:{id:project.sourceId!}});const r=await ai("/v1/ingest",{url:p.sourceUrl,output_dir:path.resolve(process.env.MEDIA_STORAGE_ROOT||"../storage","sources")});const a=await db.mediaAsset.create({data:{sourceId:source.id,storageKey:r.media_path,mimeType:"video/mp4",durationS:r.metadata.duration,width:r.metadata.width,height:r.metadata.height,fps:r.metadata.fps,codec:r.metadata.codec,hasAudio:r.metadata.hasAudio}});await db.job.update({where:{id:j.id},data:{status:"TRANSCRIBING",progress:.4,payload:{...p,mediaAssetId:a.id,mediaPath:r.media_path}}});await db.job.create({data:{userId:j.userId,projectId:j.projectId,type:"TRANSCRIBE",payload:{mediaAssetId:a.id,mediaPath:r.media_path}}});return}
 if(j.type==="TRANSCRIBE"){const p=j.payload as any;const r=await ai("/v1/transcribe",{media_path:p.mediaPath});const t=await db.transcript.create({data:{mediaAssetId:p.mediaAssetId,language:r.language,text:r.text,metadata:{duration:r.duration},segments:{create:r.segments.map((s:any)=>({startS:s.start,endS:s.end,text:s.text,confidence:s.confidence,words:{create:s.words.map((w:any)=>({startS:w.start,endS:w.end,word:w.word,confidence:w.confidence}))}}))}}});await db.job.update({where:{id:j.id},data:{status:"ANALYZING",progress:.8,payload:{...p,transcriptId:t.id}}});await db.job.create({data:{userId:j.userId,projectId:j.projectId,type:"ANALYZE",payload:{transcriptId:t.id}}});await db.usage.update({where:{userId:j.userId},data:{minutesAnalyzed:{increment:(r.duration||0)/60}}}).catch(()=>{});return}
 if(j.type==="ANALYZE"){const p=j.payload as any;const t=await db.transcript.findUniqueOrThrow({where:{id:p.transcriptId},include:{segments:true}});const project=await db.project.findUniqueOrThrow({where:{id:j.projectId!}});const categoryLine=(project.customInstructions||"").split("\n").find((x:string)=>x.startsWith("Clip categories:"))||"";const categories=categoryLine.replace("Clip categories:","").split(",").map((x:string)=>x.trim()).filter(Boolean);await db.job.update({where:{id:j.id},data:{progress:.9,status:"ANALYZING"}});const r=await ai("/v1/analyze",{segments:t.segments.map(s=>({start:s.startS,end:s.endS,text:s.text})),instruction:project.customInstructions,categories});const analysis=await db.analysis.create({data:{projectId:project.id,model:"transcript-heuristic-v1",version:"2.0.0",metadata:{candidateCount:r.candidates.length}}});for(const c of r.candidates){const h=await db.highlight.create({data:{analysisId:analysis.id,startS:c.start,endS:c.end,score:c.score,category:c.category,rationale:c.rationale,features:c.features}});await db.clip.create({data:{projectId:project.id,highlightId:h.id,startS:c.start,endS:c.end,score:c.score,category:c.category,status:"CANDIDATE"}})}await finishJob(j.id);return}
 if(j.type==="RENDER"){const p=j.payload as any;const clip=await db.clip.findUniqueOrThrow({where:{id:p.clipId},include:{project:{include:{source:{include:{media:true}}}},edit:true}});const asset=clip.project.source?.media[0];if(!asset)throw new Error("Source media missing");const seg=(clip.edit?.segments as any[])?.[0];if(!seg)throw new Error("Clip edit missing");const outputKey="renders/"+clip.id+"-"+Date.now()+".mp4";const outputPath=path.resolve(process.env.MEDIA_STORAGE_ROOT||"../storage",outputKey);const r=await ai("/v1/render",{input_path:path.resolve(process.env.MEDIA_STORAGE_ROOT||"../storage",asset.storageKey),output_path:outputPath,start:Number(seg.startS),end:Number(seg.endS),aspect:clip.edit?.aspectRatio||"9:16",segments:(clip.edit?.segments as any[]).map((s:any)=>({start:Number(s.startS),end:Number(s.endS)}))});await db.render.update({where:{id:p.renderId},data:{status:"READY",storageKey:outputKey,mimeType:"video/mp4",durationS:Number(seg.endS)-Number(seg.startS)}});await db.clip.update({where:{id:clip.id},data:{status:"READY"}});await finishJob(j.id);return}
 throw new Error("Unknown job type: "+j.type)
}catch(e){await failJob(j.id,e instanceof Error?e.message:String(e))}}
async function main(){console.log("[worker] started");for(;;){await tick();await sleep(1000)}}main().catch(e=>{console.error(e);process.exit(1)});
